In [1]:
import numpy as np
import os
import librosa
 
path = "C:/Users/srush/Downloads/Stethaim/my_Trial1" 
files = os.listdir(path+"/COPD")
x = np.array(files)
print(x)
print(x.shape)

['102_1b1_Ar_sc_Meditron.wav' '103_2b2_Ar_mc_LittC2SE.wav'
 '104_1b1_Al_sc_Litt3200.wav' '106_2b1_Pr_mc_LittC2SE.wav'
 '107_2b3_Al_mc_AKGC417L.wav' '109_1b1_Al_sc_Litt3200.wav'
 '110_1p1_Al_sc_Meditron.wav' '111_1b3_Tc_sc_Meditron.wav'
 '112_1b1_Ar_sc_Meditron.wav' '113_1b1_Al_sc_Litt3200.wav'
 '114_1b4_Al_mc_AKGC417L.wav' '116_1b2_Tc_sc_Meditron.wav'
 '117_1b2_Tc_mc_LittC2SE.wav' '118_1b1_Al_sc_Litt3200.wav'
 '120_1b1_Al_sc_Meditron.wav' '121_1p1_Tc_sc_Meditron.wav'
 '122_2b3_Al_mc_LittC2SE.wav' '123_1b1_Al_sc_Meditron.wav'
 '124_1b1_Al_sc_Litt3200.wav' '125_1b1_Tc_sc_Meditron.wav'
 '126_1b1_Al_sc_Meditron.wav' '127_1b1_Ar_sc_Meditron.wav'
 '128_1b3_Tc_mc_LittC2SE.wav' '130_1p2_Al_mc_AKGC417L.wav'
 '132_2b1_Lr_mc_LittC2SE.wav' '133_2p2_Al_mc_AKGC417L.wav'
 '134_2b1_Al_mc_LittC2SE.wav' '135_2b2_Al_mc_LittC2SE.wav'
 '136_1b1_Ar_sc_Meditron.wav' '138_1p2_Pl_mc_AKGC417L.wav'
 '139_1b1_Al_sc_Litt3200.wav' '140_2b3_Ll_mc_LittC2SE.wav'
 '141_1b2_Ar_mc_LittC2SE.wav' '142_1b1_Pl_mc_LittC2SE.wa

In [2]:
import pandas as pd

chosen_pids= pd.read_csv(path+"/ylabels/chosen_pid.csv")
diseases = chosen_pids['Disease']
diseases

0       Healthy
1        Asthma
2          COPD
3          COPD
4          COPD
        ...    
84      Healthy
85    Pneumonia
86      Healthy
87      Healthy
88    Pneumonia
Name: Disease, Length: 89, dtype: object

In [3]:
diseases.value_counts()

COPD              44
Healthy           26
Bronchiectasis     7
Pneumonia          6
Bronchiolitis      5
Asthma             1
Name: Disease, dtype: int64

In [4]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
y= label_encoder.fit_transform(diseases)
y

array([4, 0, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 4, 5, 4, 3, 4, 4, 4,
       3, 3, 3, 3, 3, 5, 4, 3, 3, 5, 3, 3, 4, 4, 3, 3, 3, 2, 3, 4, 4, 3,
       3, 3, 3, 3, 4, 3, 2, 3, 3, 3, 2, 1, 1, 3, 4, 3, 3, 3, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 3, 4, 5, 4, 1, 1, 4, 2, 4, 4, 4, 1, 2, 4, 5, 4, 4,
       5])

In [5]:
#sr =22050
file0, fs = librosa.load(path+"/COPD/"+files[0])
file0.shape

(441000,)

In [6]:
file0

array([ 0.00281204,  0.00424882,  0.00363448, ..., -0.01351928,
       -0.01411754, -0.01586503], dtype=float32)

In [87]:
mfcc0= librosa.feature.mfcc(y=file0, sr=fs)
mfcc0.shape

(20, 862)

In [88]:
mfcc0

array([[-4.73800293e+02, -4.73387695e+02, -5.33539490e+02, ...,
        -5.59948975e+02, -5.28503845e+02, -4.37487183e+02],
       [ 2.03323517e+02,  2.13104126e+02,  1.60924103e+02, ...,
         1.65051361e+02,  1.63385818e+02,  1.27486916e+02],
       [ 3.95224266e+01,  4.97598038e+01,  4.51722412e+01, ...,
         9.69565353e+01,  6.71561279e+01,  4.18637238e+01],
       ...,
       [ 8.94394875e+00,  7.11337280e+00,  7.69754362e+00, ...,
         2.03286219e+00,  6.86473608e-01, -2.49903232e-01],
       [ 9.56121826e+00,  7.21283960e+00,  2.37271500e+00, ...,
         4.24898720e+00, -1.18030131e-01, -8.69750261e-01],
       [-2.58822441e+00, -1.03840828e+00,  3.88324118e+00, ...,
         3.55745125e+00,  1.51277423e-01,  7.83264637e-01]], dtype=float32)

In [93]:
mfcc0_data=pd.DataFrame(mfcc0)
mfcc0_data

0           1           2           3           4           5    \
0  -473.800293 -473.387695 -533.539490 -604.265381 -611.765869 -612.272888   
1   203.323517  213.104126  160.924103   97.384949   93.450531   93.441299   
2    39.522427   49.759804   45.172241   31.276655   37.761261   38.796066   
3   -15.894825  -11.818619    7.692662    3.420074   10.211664   11.271423   
4   -27.443352  -14.872335   20.752539   23.688496   22.980061   23.670382   
5    -6.899246    3.281651   28.346100   46.108429   42.662811   43.750801   
6    25.824448   28.383930   27.742786   40.136513   41.760551   43.215099   
7    18.137081   21.492340   19.906136   21.168404   27.180922   27.389149   
8     9.208771   10.394516   12.410404   13.005598   17.340897   15.393307   
9    11.663536   15.110844   14.006332   14.865142   15.204596   12.653519   
10    0.568773    3.715902    7.479209   15.072548   13.802247   12.716949   
11    0.195722   -5.083578   -6.520607   12.917811   12.083853   12.231283   
12    8.142386    5.019523   -4.743193   13.008623   12.543568   12.102837   
13    2.611939    3.707514    2.652740   12.529404   12.224051   10.833176   
14    0.544071   -2.087803   -0.735927    7.154490    7.466051    6.763295   
15    4.572216    2.847161    0.484379    1.490774    2.467325    3.414217   
16    4.315589    5.102689    8.876566    2.843675    3.613955    4.897300   
17    8.943949    7.113373    7.697544    8.931463    8.438330    8.295550   
18    9.561218    7.212840    2.372715   10.609175    8.610012    7.142196   
19   -2.588224   -1.038408    3.883241    4.887075    2.496704    1.284695   

           6           7           8           9    ...         852  \
0  -609.199646 -608.512146 -610.973145 -610.389465  ... -544.351868   
1    96.074127   98.412750   98.330353   98.716858  ...  178.393311   
2    38.423546   42.363220   47.604378   46.900002  ...   93.507904   
3    10.091283   12.513442   17.571938   15.941978  ...   27.252337   
4    23.919525   23.096478   23.116417   21.958918  ...    8.397433   
5    44.132088   42.432487   39.634560   40.764725  ...   15.017979   
6    40.231003   40.633232   40.142056   43.736980  ...   15.529348   
7    20.078197   22.129135   24.489922   28.137899  ...    5.196387   
8     7.281137    8.355206    9.821774   10.749809  ...   -1.620562   
9     8.303967    7.509505    6.239417    4.494797  ...    1.406921   
10   13.217249   12.222744   10.269079    8.258179  ...    6.170779   
11   14.869785   15.551032   14.723313   13.313313  ...    4.970321   
12   13.722151   16.425991   15.770534   12.912624  ...    0.131370   
13   10.317883   13.963843   12.536085    7.055301  ...   -2.080133   
14    4.684782    7.437935    6.631095    1.302835  ...   -0.180017   
15    0.918267    1.275776    2.259389    0.594111  ...    2.656175   
16    3.502946    1.815916    2.639204    3.772415  ...    3.984319   
17    9.511340    8.014063    6.025119    5.804484  ...    4.420971   
18   11.048134   11.424095    7.882390    4.808311  ...    5.316236   
19    5.789842    7.163401    6.596468    3.611542  ...    6.127321   

           853         854         855         856         857         858  \
0  -544.000061 -542.838684 -546.444824 -555.725403 -556.499329 -554.125061   
1   178.884064  181.216782  178.458618  169.305634  168.937683  172.252594   
2    93.721436   96.586914   98.639557   97.622879   98.774895  101.876862   
3    26.697754   27.908470   32.958649   37.480366   39.814419   42.252411   
4     6.880308    5.197159    9.518634   14.890688   17.791435   18.911188   
5    12.517673    9.404474   11.290596   16.264076   19.755337   19.253124   
6    11.744569    9.444600   10.246290   16.377705   21.032360   19.181538   
7     0.174760   -0.695340    0.768294    7.865796   13.989866   11.053864   
8    -6.306664   -6.639800   -5.036818    0.075278    7.000961    3.100247   
9    -0.488421   -1.335069   -1.565897   -0.199264    5.863703    2.123492   
10    7.773568    5.83

In [89]:
X=[]

In [90]:
for file in files:
    fl, sr = librosa.load(path+"/COPD/"+file)
    mfccs = librosa.feature.mfcc(y=fl)
    X.append(np.mean(mfccs, axis=1))

In [91]:
X=np.array(X)
X.shape

(89, 20)

In [100]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [101]:
X_train.shape, X_test.shape

((44, 20), (45, 20))

In [102]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [103]:
y_actu = label_encoder.inverse_transform(y_test)
y_pre = model.predict(X_test)
y_hat = label_encoder.inverse_transform(y_pre)

In [104]:
comp ={'Predicted values':y_hat, 'Actual values':y_actu}
pd.DataFrame(comp)

Predicted values   Actual values
0           Healthy            COPD
1           Healthy   Bronchiolitis
2              COPD            COPD
3           Healthy            COPD
4           Healthy   Bronchiolitis
5              COPD            COPD
6              COPD         Healthy
7           Healthy         Healthy
8           Healthy         Healthy
9           Healthy          Asthma
10          Healthy       Pneumonia
11          Healthy         Healthy
12          Healthy   Bronchiolitis
13             COPD            COPD
14    Bronchiolitis         Healthy
15             COPD            COPD
16             COPD            COPD
17   Bronchiectasis         Healthy
18             COPD            COPD
19             COPD            COPD
20             COPD            COPD
21             COPD            COPD
22          Healthy         Healthy
23          Healthy            COPD
24          Healthy            COPD
25             COPD            COPD
26             COPD            COPD
27             COPD         Healthy
28          Healthy       Pneumonia
29          Healthy         Healthy
30             COPD            COPD
31          Healthy         Healthy
32             COPD            COPD
33          Healthy       Pneumonia
34          Healthy  Bronchiectasis
35             COPD            COPD
36             COPD            COPD
37             COPD            COPD
38             COPD            COPD
39          Healthy         Healthy
40             COPD            COPD
41          Healthy         Healthy
42   Bronchiectasis         Healthy
43             COPD            COPD
44             COPD         Healthy

In [105]:
model.score(X_test, y_test)

0.6