In [31]:
import numpy as np
import pandas as pd
import os
import librosa
#from tqdm.notebook import tqdm
# "" 
path = "./Respiratory_Sound_Database/audio_and_txt_files" 
files = []
for f in os.listdir(path):
    if f.split(".")[-1]=="wav":
        files.append(f)
#files

In [32]:
x = np.array(files)
#print(x)
print(x.shape)

(920,)


In [33]:
patient_dia= pd.read_csv("./Respiratory_Sound_Database/patient_diagnosis.csv")
patient_dia.set_index('pid',inplace=True)
patient_dia

disease
pid           
101       URTI
102    Healthy
103     Asthma
104       COPD
105       URTI
..         ...
222       COPD
223       COPD
224    Healthy
225    Healthy
226  Pneumonia

[126 rows x 1 columns]

In [34]:
diseases = patient_dia['disease']
diseases

pid
101         URTI
102      Healthy
103       Asthma
104         COPD
105         URTI
         ...    
222         COPD
223         COPD
224      Healthy
225      Healthy
226    Pneumonia
Name: disease, Length: 126, dtype: object

In [35]:
diseases.value_counts()

COPD              64
Healthy           26
URTI              14
Bronchiectasis     7
Pneumonia          6
Bronchiolitis      6
LRTI               2
Asthma             1
Name: disease, dtype: int64

In [36]:
y_labels=[]

for file in files:
    pid = int(file.split("_")[0])
    y_labels.append(diseases[pid])

y_labels[:10]

['URTI',
 'URTI',
 'Healthy',
 'Asthma',
 'COPD',
 'COPD',
 'COPD',
 'COPD',
 'COPD',
 'COPD']

In [37]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
y= label_encoder.fit_transform(y_labels)
y[:20]

array([7, 7, 4, 0, 3, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 3, 3, 3, 3],
      dtype=int64)

In [38]:
files[:10]

['101_1b1_Al_sc_Meditron.wav',
 '101_1b1_Pr_sc_Meditron.wav',
 '102_1b1_Ar_sc_Meditron.wav',
 '103_2b2_Ar_mc_LittC2SE.wav',
 '104_1b1_Al_sc_Litt3200.wav',
 '104_1b1_Ar_sc_Litt3200.wav',
 '104_1b1_Ll_sc_Litt3200.wav',
 '104_1b1_Lr_sc_Litt3200.wav',
 '104_1b1_Pl_sc_Litt3200.wav',
 '104_1b1_Pr_sc_Litt3200.wav']

In [39]:
#sr =22050
file0, fs = librosa.load(path+"/"+files[0])
file0.shape

(441000,)

In [40]:
file0

array([0.06902321, 0.10318135, 0.09086043, ..., 0.08216032, 0.08103456,
       0.08537586], dtype=float32)

In [41]:
mfcc0= librosa.feature.mfcc(y=file0, sr=fs)
mfcc0.shape

(20, 862)

In [42]:
mfcc0

array([[-282.1024   , -347.06177  , -526.26855  , ..., -521.92267  ,
        -406.40598  , -289.31357  ],
       [ 122.18912  ,  124.44951  ,  107.86206  , ...,  113.70073  ,
         123.36837  ,  109.003105 ],
       [  13.666062 ,   17.754288 ,   70.18554  , ...,   77.03856  ,
          40.73402  ,   27.640047 ],
       ...,
       [   7.6162567,    7.7836895,    2.3463209, ...,    6.1596327,
           7.554514 ,    5.9577084],
       [   2.139107 ,    4.0958548,    2.901174 , ...,    4.7241554,
           5.9255967,    4.836587 ],
       [   7.1877527,    7.299374 ,    4.9591923, ...,    4.303367 ,
           5.7839146,    5.1229453]], dtype=float32)

In [43]:
mfcc0_data=pd.DataFrame(mfcc0)
mfcc0_data

0           1           2           3           4           5    \
0  -282.102386 -347.061768 -526.268555 -529.715393 -533.798340 -533.643066   
1   122.189117  124.449509  107.862061  104.294067   99.344963   98.707108   
2    13.666062   17.754288   70.185539   68.842949   65.753265   62.971664   
3    32.476734   34.216236   38.228054   37.404724   35.876495   30.888109   
4    10.168023   13.816444   24.605679   22.781868   21.581432   15.875908   
5    20.162477   21.619400   21.221867   19.395054   17.508921   13.399963   
6     6.682316    9.962695   15.961784   16.049698   13.557902   12.556527   
7    14.821116   15.882987    8.701469   10.430472    8.279190    9.885613   
8     4.702484    7.653846    7.402489    8.332818    7.230632    9.440435   
9    11.797634   12.768690   13.688175   12.390888   11.988113   13.158165   
10    3.355582    6.269678   19.316011   17.143421   16.461197   16.625931   
11    9.969526   10.826794   17.034307   16.123299   14.878353   15.144207   
12    2.727022    5.352603    9.406879   10.072847    9.407190   10.265173   
13    8.801946    9.349096    4.126810    5.374764    6.933677    7.581333   
14    2.061586    4.391915    3.932614    5.776532    9.859137    9.308435   
15    7.711519    8.040598    4.997100    8.482661   13.220037   11.710545   
16    1.891273    3.985940    3.966965    8.611610   11.272652   10.198511   
17    7.616257    7.783689    2.346321    5.274732    4.605256    5.155528   
18    2.139107    4.095855    2.901174    1.921684   -0.748036    1.556329   
19    7.187753    7.299374    4.959192    1.741133   -0.221002    3.425899   

           6           7           8           9    ...         852  \
0  -535.404541 -520.218628 -507.520142 -513.118774  ... -504.585083   
1    97.225349  118.714119  134.614166  126.738098  ...  132.134354   
2    63.654453   85.207840   96.633881   89.110199  ...   82.075058   
3    33.087601   54.369011   62.097767   55.802544  ...   42.912865   
4    17.782530   37.301502   43.485809   39.773273  ...   29.138689   
5    13.602999   29.017059   34.620518   34.622829  ...   26.713737   
6    11.207798   21.091934   25.456800   29.162073  ...   21.168301   
7     8.599993   13.875101   16.155952   22.069056  ...   15.563791   
8     9.971238   13.161823   13.388771   19.154608  ...   17.808023   
9    15.776230   18.850849   17.746716   21.289742  ...   23.735569   
10   19.630976   22.875902   21.407379   21.865189  ...   22.548607   
11   16.272371   19.111412   18.361816   16.413033  ...   12.825766   
12    8.881266   11.061150   11.798059    9.244976  ...    3.415498   
13    5.338775    6.945796    8.780997    7.420034  ...    0.275117   
14    8.390165    9.291321   10.707808   11.090752  ...    0.551330   
15   12.615837   12.643829   12.570089   13.781513  ...    0.011339   
16   11.640848   11.172750   10.477433   11.349024  ...   -0.811313   
17    5.889407    5.396755    6.144751    6.666290  ...   -0.237778   
18    1.510694    0.275727    3.215870    4.428267  ...    0.280418   
19    2.889159   -1.036964    2.219625    4.658573  ...   -0.917899   

           853         854         855         856         857         858  \
0  -532.222168 -537.750549 -538.156433 -539.476440 -541.593384 -538.645630   
1   100.776489   91.952393   91.340149   88.820137   86.255692   92.071945   
2    66.592613   56.181953   55.376266   52.614922   50.750427   58.665039   
3    38.388382   28.574072   27.599083   27.143204   25.327419   31.443062   
4    26.323114   20.201916   19.721519   22.567471   20.247847   21.391476   
5    22.245209   20.486206   21.309689   24.904610   22.601271   20.939106   
6    17.121601   17.008091   18.921474   20.278210   19.112640   19.767414   
7    12.838624   11.222319   12.900288   12.309086   12.665523   17.458336   
8    14.692081   11.369467   11.667967   11.588990   12.718096   18.354258   
9    20.089954   17.219038   15.966759   17.194603   18.281479   21.005886   
10   20.831841   19.42

In [44]:
X=[]

In [46]:
for file in (files):
    fl, sr = librosa.load(path+"/"+file)
    mfccs = librosa.feature.mfcc(y=fl)
    X.append(np.mean(mfccs, axis=1))  

KeyboardInterrupt: 

In [ ]:
X=np.array(X)
X.shape


(920, 20)

In [ ]:
X = pd.DataFrame(X)
X

0           1          2          3          4          5   \
0   -528.427490  104.520699  69.904068  42.575790  31.209564  27.494476   
1   -582.506165   95.396805  57.399883  31.437761  28.146194  33.530159   
2   -596.806458  116.010277  60.591980  25.570784  26.232788  38.502319   
3   -418.434662   68.258110  48.023357  33.066364  27.972254  26.458151   
4   -441.498138  100.994850  74.064911  43.247185  19.708635   7.844025   
..          ...         ...        ...        ...        ...        ...   
915 -547.458984   76.001320  54.615574  41.038040  34.075874  29.128040   
916 -533.142456   99.107254  55.932369  30.749420  24.889029  25.753965   
917 -520.420898  102.170929  62.050446  36.298801  32.737335  33.513817   
918 -484.383331   85.328377  64.264946  45.740410  36.413624  32.995514   
919 -520.003784   85.682472  60.131535  42.650108  38.514229  37.340477   

            6          7          8          9          10         11  \
0    22.203037  16.555120  15.272655  16.684355  14.638173   8.430954   
1    31.566959  22.795122  16.640436  15.635400  14.028157   9.275003   
2    36.033993  18.649771   3.547745   0.806175   5.736948   9.667266   
3    22.680613  18.160683  15.905028  15.107646  13.299389  10.849195   
4     5.499160   8.011956  11.730556  14.880559  16.778522  17.138746   
..         ...        ...        ...        ...        ...        ...   
915  23.931993  19.739443  16.812328  14.838124  12.996349  11.298636   
916  25.999796  22.928568  19.637295  18.210997  14.211654   8.145342   
917  25.237780  13.636399   8.804965   9.768736   9.373283   6.514682   
918  28.544821  21.263481  14.468318  11.192873  10.615379  10.136909   
919  29.413401  17.162458   8.781700   7.346933   8.915624   9.459752   

            12         13         14         15        16        17        18  \
0     3.853199   4.909301   8.395902   9.314491  6.849532  3.967180  2.853413   
1     5.843849   7.337840  10.571301  10.618855  7.161932  3.731207  2.662667   
2     9.134168   5.529873   2.173072   2.107794  5.250319  7.925583  7.093313   
3     9.627755   9.750741   9.569046   8.601937  7.694519  7.173669  6.369511   
4    15.962942  13.537178  10.294417   6.756285  3.601534  1.559564  1.009744   
..         ...        ...        ...        ...       ...       ...       ...   
915   9.774643   8.957767   8.174731   7.454870  6.683159  6.214869  5.994518   
916   6.237601   9.103200  11.487430  10.652189  7.475088  4.302876  3.311296   
917   5.564125   7.136012   7.164575   4.425546  2.634963  4.292336  6.852127   
918   8.468866   6.371399   4.965974   4.697912  5.214182  5.864259  5.957247   
919   8.477821   7.114070   5.834986   5.007944  5.086992  6.013876  6.752820   

           19  
0    3.390551  
1    3.652575  
2    4.064556  
3    5.585998  
4    1.665756  
..        ...  
915  5.934742  
916  4.680158  
917  6.658884  
918  5.357391  
919  6.482968  

[920 rows x 20 columns]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, shuffle=True)

In [ ]:
X_train.shape, X_test.shape

((552, 20), (368, 20))

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
y_actu = label_encoder.inverse_transform(y_test)
y_pre = model.predict(X_test)
y_hat = label_encoder.inverse_transform(y_pre)

In [ ]:
comp ={'Predicted values':y_hat, 'Actual values':y_actu}
pd.DataFrame(comp)

Predicted values   Actual values
0               COPD            URTI
1               COPD            COPD
2               COPD  Bronchiectasis
3          Pneumonia            URTI
4               COPD            COPD
..               ...             ...
363             COPD            COPD
364             COPD            COPD
365             COPD            COPD
366             COPD            COPD
367             COPD            COPD

[368 rows x 2 columns]

In [ ]:
accu=model.score(X_test, y_test)
accu

0.8967391304347826

In [ ]:
print("The Accuracy is",accu*100 ,"%")

The Accuracy is 89.67391304347827 %


In [ ]:
y_pred_prob= model.predict_proba(X_test)
y_pred_prob

array([[0.  , 0.07, 0.07, ..., 0.03, 0.15, 0.08],
       [0.  , 0.03, 0.02, ..., 0.  , 0.11, 0.03],
       [0.  , 0.16, 0.  , ..., 0.  , 0.02, 0.07],
       ...,
       [0.01, 0.  , 0.02, ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.06, 0.  ]])

In [ ]:
pred_wid_prob = []

for pred in y_pred_prob:
    stri=""
    for i in pred:
        if i>0.1:
            j = np.where(pred==i)[0]
            dise = label_encoder.inverse_transform(j)
            stri+=( str(round(i*100,2))+"% "+dise[0]+", ")
        #stri+="\n"
    pred_wid_prob.append(stri)
pred_wid_prob

['42.0% COPD, 18.0% Healthy, 15.0% Pneumonia, ',
 '76.0% COPD, 11.0% Pneumonia, ',
 '16.0% Bronchiectasis, 70.0% COPD, ',
 '27.0% COPD, 28.0% Healthy, 31.0% Pneumonia, ',
 '86.0% COPD, ',
 '99.0% COPD, ',
 '91.0% COPD, ',
 '82.0% COPD, ',
 '98.0% COPD, ',
 '97.0% COPD, ',
 '36.0% COPD, 15.0% Healthy, 45.0% Pneumonia, ',
 '56.0% COPD, 14.0% Healthy, 20.0% Pneumonia, ',
 '83.0% COPD, ',
 '95.0% COPD, ',
 '99.0% COPD, ',
 '98.0% COPD, ',
 '100.0% COPD, ',
 '15.0% Bronchiolitis, 52.0% COPD, 20.0% URTI, ',
 '90.0% COPD, ',
 '99.0% COPD, ',
 '97.0% COPD, ',
 '85.0% COPD, 12.0% Pneumonia, ',
 '100.0% COPD, ',
 '89.0% COPD, ',
 '100.0% COPD, ',
 '96.0% COPD, ',
 '98.0% COPD, ',
 '94.0% COPD, ',
 '93.0% COPD, ',
 '82.0% COPD, ',
 '46.0% COPD, 31.0% Pneumonia, ',
 '100.0% COPD, ',
 '100.0% COPD, ',
 '100.0% COPD, ',
 '42.0% COPD, 15.0% Healthy, 28.0% URTI, ',
 '98.0% COPD, ',
 '100.0% COPD, ',
 '93.0% COPD, ',
 '34.0% COPD, 28.0% Healthy, 24.0% Pneumonia, ',
 '90.0% COPD, ',
 '91.0% COPD, ',
 '8

In [ ]:
final_res ={ 'Given Disease':y_hat ,'Our prediction':pred_wid_prob }
results = pd.DataFrame(final_res)
results

Given Disease                                Our prediction
0            COPD  42.0% COPD, 18.0% Healthy, 15.0% Pneumonia, 
1            COPD                 76.0% COPD, 11.0% Pneumonia, 
2            COPD            16.0% Bronchiectasis, 70.0% COPD, 
3       Pneumonia  27.0% COPD, 28.0% Healthy, 31.0% Pneumonia, 
4            COPD                                  86.0% COPD, 
..            ...                                           ...
363          COPD                                 100.0% COPD, 
364          COPD            12.0% Bronchiectasis, 67.0% COPD, 
365          COPD                                  96.0% COPD, 
366          COPD                                 100.0% COPD, 
367          COPD                                  93.0% COPD, 

[368 rows x 2 columns]

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_actu, y_hat)

array([[  1,   0,   5,   0,   0,   0,   0],
       [  0,   0,   4,   0,   0,   1,   0],
       [  0,   0, 322,   0,   0,   1,   0],
       [  1,   0,   8,   3,   0,   1,   1],
       [  0,   0,   0,   0,   0,   1,   0],
       [  0,   0,   9,   0,   0,   3,   0],
       [  0,   0,   4,   1,   0,   1,   1]], dtype=int64)