In [5]:
import numpy as np
import os
import librosa
 
path = "C:/Users/srush/Downloads/Stethaim/my_Trial1" 
files = os.listdir("./COPD")
x = np.array(files)
print(x)
print(x.shape)

['102_1b1_Ar_sc_Meditron.wav' '103_2b2_Ar_mc_LittC2SE.wav'
 '104_1b1_Al_sc_Litt3200.wav' '106_2b1_Pr_mc_LittC2SE.wav'
 '107_2b3_Al_mc_AKGC417L.wav' '109_1b1_Al_sc_Litt3200.wav'
 '110_1p1_Al_sc_Meditron.wav' '111_1b3_Tc_sc_Meditron.wav'
 '112_1b1_Ar_sc_Meditron.wav' '113_1b1_Al_sc_Litt3200.wav'
 '114_1b4_Al_mc_AKGC417L.wav' '116_1b2_Tc_sc_Meditron.wav'
 '117_1b2_Tc_mc_LittC2SE.wav' '118_1b1_Al_sc_Litt3200.wav'
 '120_1b1_Al_sc_Meditron.wav' '121_1p1_Tc_sc_Meditron.wav'
 '122_2b3_Al_mc_LittC2SE.wav' '123_1b1_Al_sc_Meditron.wav'
 '124_1b1_Al_sc_Litt3200.wav' '125_1b1_Tc_sc_Meditron.wav'
 '126_1b1_Al_sc_Meditron.wav' '127_1b1_Ar_sc_Meditron.wav'
 '128_1b3_Tc_mc_LittC2SE.wav' '130_1p2_Al_mc_AKGC417L.wav'
 '132_2b1_Lr_mc_LittC2SE.wav' '133_2p2_Al_mc_AKGC417L.wav'
 '134_2b1_Al_mc_LittC2SE.wav' '135_2b2_Al_mc_LittC2SE.wav'
 '136_1b1_Ar_sc_Meditron.wav' '138_1p2_Pl_mc_AKGC417L.wav'
 '139_1b1_Al_sc_Litt3200.wav' '140_2b3_Ll_mc_LittC2SE.wav'
 '141_1b2_Ar_mc_LittC2SE.wav' '142_1b1_Pl_mc_LittC2SE.wa

In [6]:
import pandas as pd

chosen_pids= pd.read_csv("./ylabels/chosen_pid.csv")
diseases = chosen_pids['Disease']
diseases

0       Healthy
1        Asthma
2          COPD
3          COPD
4          COPD
        ...    
84      Healthy
85    Pneumonia
86      Healthy
87      Healthy
88    Pneumonia
Name: Disease, Length: 89, dtype: object

In [7]:
diseases.value_counts()

COPD              44
Healthy           26
Bronchiectasis     7
Pneumonia          6
Bronchiolitis      5
Asthma             1
Name: Disease, dtype: int64

In [8]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
y= label_encoder.fit_transform(diseases)
y

array([4, 0, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 4, 5, 4, 3, 4, 4, 4,
       3, 3, 3, 3, 3, 5, 4, 3, 3, 5, 3, 3, 4, 4, 3, 3, 3, 2, 3, 4, 4, 3,
       3, 3, 3, 3, 4, 3, 2, 3, 3, 3, 2, 1, 1, 3, 4, 3, 3, 3, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 3, 4, 5, 4, 1, 1, 4, 2, 4, 4, 4, 1, 2, 4, 5, 4, 4,
       5])

In [9]:
#sr =22050
file0, fs = librosa.load("./COPD/"+files[0])
file0.shape

(441000,)

In [10]:
file0

array([ 0.00281204,  0.00424882,  0.00363448, ..., -0.01351928,
       -0.01411754, -0.01586503], dtype=float32)

In [11]:
mfcc0= librosa.feature.mfcc(y=file0)
mfcc0.shape

(20, 862)

In [12]:
mfcc0

array([[-4.73800293e+02, -4.73387695e+02, -5.33539490e+02, ...,
        -5.59948975e+02, -5.28503845e+02, -4.37487183e+02],
       [ 2.03323517e+02,  2.13104126e+02,  1.60924103e+02, ...,
         1.65051361e+02,  1.63385818e+02,  1.27486916e+02],
       [ 3.95224266e+01,  4.97598038e+01,  4.51722412e+01, ...,
         9.69565353e+01,  6.71561279e+01,  4.18637238e+01],
       ...,
       [ 8.94394875e+00,  7.11337280e+00,  7.69754362e+00, ...,
         2.03286219e+00,  6.86473608e-01, -2.49903232e-01],
       [ 9.56121826e+00,  7.21283960e+00,  2.37271500e+00, ...,
         4.24898720e+00, -1.18030131e-01, -8.69750261e-01],
       [-2.58822441e+00, -1.03840828e+00,  3.88324118e+00, ...,
         3.55745125e+00,  1.51277423e-01,  7.83264637e-01]], dtype=float32)

In [13]:
X=[]

In [14]:
for file in files:
    fl, sr = librosa.load("./COPD/"+file)
    mfccs = librosa.feature.mfcc(y=fl)
    X.append(np.mean(mfccs, axis=1))

In [15]:
X=np.array(X)
X.shape

(89, 20)

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [17]:
X_train.shape

(71, 20)

In [18]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [19]:
model.score(X_test, y_test)

0.8333333333333334

In [20]:
import pickle

pickle.dump(model, open('Prot0.pkl','wb'))